# Generated by Django 5.2.7 on 2025-10-22 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('art_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_uid', models.OneToOneField(db_column='profile_uid', on_delete=django.db.models.deletion.CASCADE, related_name='profile_bio', to='main.users')),
            ],
            options={
                'db_table': 'profile_bio',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(db_column='art_id', on_delete=django.db.models.deletion.CASCADE, to='main.arts')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_uid', models.ForeignKey(db_column='receiver_uid', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='main.users')),
                ('sender_uid', models.ForeignKey(db_column='sender_uid', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='main.users')),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='arts',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.CreateModel(
            name='ArtLikes',
            fields=[
                ('like_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(db_column='art_id', on_delete=django.db.models.deletion.CASCADE, to='main.arts')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'db_table': 'art_likes',
                'managed': True,
            },
        ),
    ]
