# Generated by Django 5.2.7 on 2025-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='category',
            field=models.CharField(choices=[('3D Art', '3D Art'), ('2D Art', '2D Art'), ('Pixel Art', 'Pixel Art'), ('Concept Art', 'Concept Art'), ('Illustration', 'Illustration'), ('Sculptures', 'Sculptures'), ('Motion Graphics', 'Motion Graphics'), ('Animation', 'Animation'), ('Photography', 'Photography'), ('Game Assets', 'Game Assets')], default='2D Art', max_length=50),
        ),
    ]
